apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: iulianstave/auth
    context: auth
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*